### ISSUE TITLE
REVIEW Week7

### ISSUE THREAD

**Issue by tienyulin** [SOA-nuts/GoogleNewsAPI#12]
1. Recommend not abbreviating the variable name if that is not a common abbreviation like `cmp` is not a common abbreviation of `company`. I would suggest just using `company` or `company_name`.
https://github.com/SOA-nuts/GoogleNewsAPI/blob/master/app/controllers/app.rb#L29

2. Don't put useless code into version control, even if you comment those codes to make them not work. I only list one here, but there are some other codes like that. Please remove them. It will make the code untidy.
https://github.com/SOA-nuts/GoogleNewsAPI/blob/master/app/models/gateways/google_news_api.rb#L33

3. What is the file `.rake_tasks~` for?
https://github.com/SOA-nuts/GoogleNewsAPI/blob/master/.rake_tasks%7E
@ChungYiTsai

**Comment by ChungYiTsai** [comment]
Got it, thanks for the suggestions. Will modify this week.
About `.rake_tasks~` , I have no idea why it is here. I remember I have not create it.
I will delete it this week.
